# See https://aka.ms/yaml
# This pipeline to be run on PRs

trigger: none
pr:
  branches:
    include:
    - master
    - v*.*.x
  paths:
    exclude:
    - .gitignore
    - .readthedocs.yaml
    - contrib/pr_merge_check.py
    - docs/source
    - docs/CodeStyle.md
    - docs/LoggingStyle.md
    - docs/OptimizationStyle.md
    - README.md
    - NEWS
    - AUTHORS

stages:
  - stage: Test
    jobs:
      - job: Gtest
        workspace:
          clean: all
        pool:
          name: MLNX
          demands:
          - ucx_bf -equals yes
        steps:
          - checkout: self

          - bash: |
              set -eE
              git clone --depth 1 -b master https://github.com/openucx/ucx.git ucx
              cd ucx
              ./autogen.sh
              mkdir -p ucx_build_dir
              cd ucx_build_dir
              ../configure --without-java --prefix=$(Build.Repository.LocalPath)/install_ucx
              gcc -v
              make -s -j `nproc`
              make install
            displayName: Build ucx artifact
          - bash: |
              set -xEe
              ./autogen.sh
              mkdir -p build
              cd build
              ../configure --with-ucx=$(Build.Repository.LocalPath)/install_ucx \
                            --prefix=$(Build.Repository.LocalPath)/install --enable-gtest
              make -j install
            displayName: Build ucc artifact
          - bash: |
              cd build
              make gtest
            displayName: Launch Gtest
